app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_company:
    resource: "@AppBundle/Resources/config/routing/department.yml"
    prefix:   /department

app_job:
    resource: "@AppBundle/Resources/config/routing/faculty.yml"
    prefix:   /faculty
