department_index:
    path:     /
    defaults: { _controller: "AppBundle:Department:index" }
    methods:  GET

department_show:
    path:     /show/{id}
    defaults: { _controller: "AppBundle:Department:show" }
    methods:  GET

department_new:
    path:     /new
    defaults: { _controller: "AppBundle:Department:new" }
    methods:  [GET, POST]

department_edit:
    path:     /edit/{id}
    defaults: { _controller: "AppBundle:Department:edit" }
    methods:  [GET, POST]

department_delete:
    path:     /delete/{id}
    defaults: { _controller: "AppBundle:Department:delete" }
    methods:  GET
