<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'my.listener2' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/EventListener/PostFaculty.php';

return $this->services['my.listener2'] = new \AppBundle\EventListener\PostFaculty();
