<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWc4pwal\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWc4pwal/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWc4pwal.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWc4pwal\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWc4pwal\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wc4pwal',
    'container.build_id' => '86e1475e',
    'container.build_time' => 1522236269,
));
